services:
    biolak-payload:
        container_name: biolak-payload
        # ports:
        #     - '3000:3000'
        image: ghcr.io/delnegend/biolak:latest
        volumes:
            - ./data/media:/home/node/app/public/media
            - ./data/data.sqlite3:/home/node/app/data.sqlite3
        env_file: .biolak.env
        networks: [biolak-network]

    cloudflared:
        container_name: cloudflared
        image: docker.io/cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel run
        env_file: .cloudflare.env
        networks: [biolak-network]

networks:
    biolak-network:
