services:
    biolak:
        container_name: biolak
        # ports:
        #     - '3000:3000'
        image: ghcr.io/delnegend/biolak:latest
        volumes: [./data:/home/node/app/data:Z]
        env_file: .biolak.env
        networks: [biolak-network]
        healthcheck:
            test: ["CMD-SHELL","curl -f http://localhost:3000/api/status || exit 1"]
            interval: 30s
            timeout: 5s
            start_period: 10s
            retries: 3

    cloudflared:
        container_name: cloudflared
        image: docker.io/cloudflare/cloudflared:latest
        restart: unless-stopped
        command: tunnel run
        env_file: .cloudflare.env
        networks: [biolak-network]

networks:
    biolak-network:
        name: biolak
