services:
   postgres-test-build:
      image: postgres:17-alpine
      restart: unless-stopped
      volumes:
         - biolak-postgres-test-build:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=biolak

   server-test-build:
      image: node:24-alpine
      depends_on:
         postgres-test-build:
            condition: service_started
      environment:
         DATABASE_URI: postgres://postgres:postgres@postgres-test-build:5432/biolak
         PAYLOAD_SECRET: YOUR_PAYLOAD_SECRET_HERE
         NEXT_PUBLIC_SERVER_URL: https://example.com
         CRON_SECRET: YOUR_CRON_SECRET_HERE
         PREVIEW_SECRET: YOUR_SECRET_HERE
      volumes:
         - ../public/:/app/public/
         - ../src/:/app/src/
         - ../redirects.js:/app/redirects.js
         - ../package.json:/app/package.json
         - ../next-sitemap.config.cjs:/app/next-sitemap.config.cjs
         - ../postcss.config.js:/app/postcss.config.js
         - ../tsconfig.json:/app/tsconfig.json
         - ../eslint.config.mjs:/app/eslint.config.mjs
         - ../tailwind.config.mjs:/app/tailwind.config.mjs
         - ../next-env.d.ts:/app/next-env.d.ts
         - ../pnpm-lock.yaml:/app/pnpm-lock.yaml
         - biolak-nextjs:/app/.next/
         - biolak-pnpm-store:/app/.pnpm-store/
         - biolak-node_modules:/app/node_modules/
      working_dir: /app
      command: sh -c "npm i -g pnpm && pnpm i --frozen-lockfile && pnpm payload migrate && pnpm next build --turbo"

volumes:
   biolak-postgres-test-build:
   biolak-nextjs:
   biolak-pnpm-store:
   biolak-node_modules:
