import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_right_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_right_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_cta_right_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_cta_right_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_products_blocks_cta_right_link_type" AS ENUM('reference', 'custom');
  DROP INDEX IF EXISTS "post_categories_rels_pages_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_post_categories_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_posts_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_product_categories_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_products_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_product_sub_categories_id_idx";
  ALTER TABLE "products_blocks_cta_center_locales" ALTER COLUMN "link_label" DROP NOT NULL;
  ALTER TABLE "products_blocks_cta_left_locales" ALTER COLUMN "link_label" DROP NOT NULL;
  ALTER TABLE "pages_blocks_cta_center_locales" ADD COLUMN "link_type" "enum_pages_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_center_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_center_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_cta_left_locales" ADD COLUMN "link_type" "enum_pages_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_left_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_left_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_call_to_action_post_locales" ADD COLUMN "link_type" "enum_pages_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_call_to_action_post_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_call_to_action_post_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_cta_right_locales" ADD COLUMN "link_type" "enum_pages_blocks_cta_right_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_right_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_right_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_cta_right_locales" ADD COLUMN "link_label" varchar;
  ALTER TABLE "_pages_v_blocks_cta_center_locales" ADD COLUMN "link_type" "enum__pages_v_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_center_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_center_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_left_locales" ADD COLUMN "link_type" "enum__pages_v_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_left_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_left_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" ADD COLUMN "link_type" "enum__pages_v_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_right_locales" ADD COLUMN "link_type" "enum__pages_v_blocks_cta_right_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_right_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_right_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_right_locales" ADD COLUMN "link_label" varchar;
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" ADD COLUMN "link_type" "enum_post_categories_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "post_categories_rels" ADD COLUMN "locale" "_locales";
  ALTER TABLE "posts_blocks_cta_center_locales" ADD COLUMN "link_type" "enum_posts_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_center_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_center_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_left_locales" ADD COLUMN "link_type" "enum_posts_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_left_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_left_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_right_locales" ADD COLUMN "link_type" "enum_posts_blocks_cta_right_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_right_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_right_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_right_locales" ADD COLUMN "link_label" varchar;
  ALTER TABLE "_posts_v_blocks_cta_center_locales" ADD COLUMN "link_type" "enum__posts_v_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_center_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_center_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_left_locales" ADD COLUMN "link_type" "enum__posts_v_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_left_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_left_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_right_locales" ADD COLUMN "link_type" "enum__posts_v_blocks_cta_right_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_right_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_right_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_right_locales" ADD COLUMN "link_label" varchar;
  ALTER TABLE "products_blocks_cta_center_locales" ADD COLUMN "link_type" "enum_products_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_center_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_center_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "products_blocks_cta_left_locales" ADD COLUMN "link_type" "enum_products_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_left_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_left_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "products_blocks_cta_right_locales" ADD COLUMN "link_type" "enum_products_blocks_cta_right_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_right_locales" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_right_locales" ADD COLUMN "link_url" varchar;
  ALTER TABLE "products_blocks_cta_right_locales" ADD COLUMN "link_label" varchar;
  CREATE INDEX IF NOT EXISTS "post_categories_rels_locale_idx" ON "post_categories_rels" USING btree ("locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_pages_id_idx" ON "post_categories_rels" USING btree ("pages_id","locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_post_categories_id_idx" ON "post_categories_rels" USING btree ("post_categories_id","locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_posts_id_idx" ON "post_categories_rels" USING btree ("posts_id","locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_product_categories_id_idx" ON "post_categories_rels" USING btree ("product_categories_id","locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_products_id_idx" ON "post_categories_rels" USING btree ("products_id","locale");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_product_sub_categories_id_idx" ON "post_categories_rels" USING btree ("product_sub_categories_id","locale");
  ALTER TABLE "pages_blocks_cta_center" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_cta_center" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_cta_center" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_cta_left" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_cta_left" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_cta_left" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_type";
  ALTER TABLE "pages_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_new_tab";
  ALTER TABLE "pages_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_url";
  ALTER TABLE "pages_blocks_cta_right_locales" DROP COLUMN IF EXISTS "button_text";
  ALTER TABLE "_pages_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_type";
  ALTER TABLE "_pages_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_url";
  ALTER TABLE "_pages_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "button_text";
  ALTER TABLE "post_categories_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "post_categories_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "post_categories_blocks_call_to_action_post" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_center" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "posts_blocks_cta_center" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "posts_blocks_cta_center" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_left" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "posts_blocks_cta_left" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "posts_blocks_cta_left" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_type";
  ALTER TABLE "posts_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_new_tab";
  ALTER TABLE "posts_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_url";
  ALTER TABLE "posts_blocks_cta_right_locales" DROP COLUMN IF EXISTS "button_text";
  ALTER TABLE "_posts_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_posts_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_center" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_posts_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_posts_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_left" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_posts_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_type";
  ALTER TABLE "_posts_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_url";
  ALTER TABLE "_posts_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "button_text";
  ALTER TABLE "products_blocks_cta_center" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "products_blocks_cta_center" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "products_blocks_cta_center" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "products_blocks_cta_left" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "products_blocks_cta_left" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "products_blocks_cta_left" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "products_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_type";
  ALTER TABLE "products_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_new_tab";
  ALTER TABLE "products_blocks_cta_right" DROP COLUMN IF EXISTS "button_link_url";
  ALTER TABLE "products_blocks_cta_right_locales" DROP COLUMN IF EXISTS "button_text";
  DROP TYPE "public"."enum_pages_blocks_cta_right_button_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_cta_right_button_link_type";
  DROP TYPE "public"."enum_posts_blocks_cta_right_button_link_type";
  DROP TYPE "public"."enum__posts_v_blocks_cta_right_button_link_type";
  DROP TYPE "public"."enum_products_blocks_cta_right_button_link_type";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_right_button_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_right_button_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_cta_right_button_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_cta_right_button_link_type" AS ENUM('reference', 'custom');
  CREATE TYPE "public"."enum_products_blocks_cta_right_button_link_type" AS ENUM('reference', 'custom');
  DROP INDEX IF EXISTS "post_categories_rels_locale_idx";
  DROP INDEX IF EXISTS "post_categories_rels_pages_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_post_categories_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_posts_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_product_categories_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_products_id_idx";
  DROP INDEX IF EXISTS "post_categories_rels_product_sub_categories_id_idx";
  ALTER TABLE "products_blocks_cta_center_locales" ALTER COLUMN "link_label" SET NOT NULL;
  ALTER TABLE "products_blocks_cta_left_locales" ALTER COLUMN "link_label" SET NOT NULL;
  ALTER TABLE "pages_blocks_cta_center" ADD COLUMN "link_type" "enum_pages_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_center" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_center" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_cta_left" ADD COLUMN "link_type" "enum_pages_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_left" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_left" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_call_to_action_post" ADD COLUMN "link_type" "enum_pages_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_call_to_action_post" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "pages_blocks_call_to_action_post" ADD COLUMN "link_url" varchar;
  ALTER TABLE "pages_blocks_cta_right" ADD COLUMN "button_link_type" "enum_pages_blocks_cta_right_button_link_type" DEFAULT 'reference';
  ALTER TABLE "pages_blocks_cta_right" ADD COLUMN "button_link_new_tab" boolean;
  ALTER TABLE "pages_blocks_cta_right" ADD COLUMN "button_link_url" varchar;
  ALTER TABLE "pages_blocks_cta_right_locales" ADD COLUMN "button_text" varchar;
  ALTER TABLE "_pages_v_blocks_cta_center" ADD COLUMN "link_type" "enum__pages_v_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_center" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_center" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_left" ADD COLUMN "link_type" "enum__pages_v_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_left" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_left" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_call_to_action_post" ADD COLUMN "link_type" "enum__pages_v_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_call_to_action_post" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_call_to_action_post" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_right" ADD COLUMN "button_link_type" "enum__pages_v_blocks_cta_right_button_link_type" DEFAULT 'reference';
  ALTER TABLE "_pages_v_blocks_cta_right" ADD COLUMN "button_link_new_tab" boolean;
  ALTER TABLE "_pages_v_blocks_cta_right" ADD COLUMN "button_link_url" varchar;
  ALTER TABLE "_pages_v_blocks_cta_right_locales" ADD COLUMN "button_text" varchar;
  ALTER TABLE "post_categories_blocks_call_to_action_post" ADD COLUMN "link_type" "enum_post_categories_blocks_call_to_action_post_link_type" DEFAULT 'reference';
  ALTER TABLE "post_categories_blocks_call_to_action_post" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "post_categories_blocks_call_to_action_post" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_center" ADD COLUMN "link_type" "enum_posts_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_center" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_center" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_left" ADD COLUMN "link_type" "enum_posts_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_left" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_left" ADD COLUMN "link_url" varchar;
  ALTER TABLE "posts_blocks_cta_right" ADD COLUMN "button_link_type" "enum_posts_blocks_cta_right_button_link_type" DEFAULT 'reference';
  ALTER TABLE "posts_blocks_cta_right" ADD COLUMN "button_link_new_tab" boolean;
  ALTER TABLE "posts_blocks_cta_right" ADD COLUMN "button_link_url" varchar;
  ALTER TABLE "posts_blocks_cta_right_locales" ADD COLUMN "button_text" varchar;
  ALTER TABLE "_posts_v_blocks_cta_center" ADD COLUMN "link_type" "enum__posts_v_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_center" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_center" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_left" ADD COLUMN "link_type" "enum__posts_v_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_left" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_left" ADD COLUMN "link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_right" ADD COLUMN "button_link_type" "enum__posts_v_blocks_cta_right_button_link_type" DEFAULT 'reference';
  ALTER TABLE "_posts_v_blocks_cta_right" ADD COLUMN "button_link_new_tab" boolean;
  ALTER TABLE "_posts_v_blocks_cta_right" ADD COLUMN "button_link_url" varchar;
  ALTER TABLE "_posts_v_blocks_cta_right_locales" ADD COLUMN "button_text" varchar;
  ALTER TABLE "products_blocks_cta_center" ADD COLUMN "link_type" "enum_products_blocks_cta_center_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_center" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_center" ADD COLUMN "link_url" varchar;
  ALTER TABLE "products_blocks_cta_left" ADD COLUMN "link_type" "enum_products_blocks_cta_left_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_left" ADD COLUMN "link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_left" ADD COLUMN "link_url" varchar;
  ALTER TABLE "products_blocks_cta_right" ADD COLUMN "button_link_type" "enum_products_blocks_cta_right_button_link_type" DEFAULT 'reference';
  ALTER TABLE "products_blocks_cta_right" ADD COLUMN "button_link_new_tab" boolean;
  ALTER TABLE "products_blocks_cta_right" ADD COLUMN "button_link_url" varchar;
  ALTER TABLE "products_blocks_cta_right_locales" ADD COLUMN "button_text" varchar;
  CREATE INDEX IF NOT EXISTS "post_categories_rels_pages_id_idx" ON "post_categories_rels" USING btree ("pages_id");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_post_categories_id_idx" ON "post_categories_rels" USING btree ("post_categories_id");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_posts_id_idx" ON "post_categories_rels" USING btree ("posts_id");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_product_categories_id_idx" ON "post_categories_rels" USING btree ("product_categories_id");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_products_id_idx" ON "post_categories_rels" USING btree ("products_id");
  CREATE INDEX IF NOT EXISTS "post_categories_rels_product_sub_categories_id_idx" ON "post_categories_rels" USING btree ("product_sub_categories_id");
  ALTER TABLE "pages_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "pages_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "pages_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "pages_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_label";
  ALTER TABLE "_pages_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_pages_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_pages_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_pages_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_label";
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "post_categories_blocks_call_to_action_post_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "post_categories_rels" DROP COLUMN IF EXISTS "locale";
  ALTER TABLE "posts_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "posts_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "posts_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "posts_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "posts_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "posts_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "posts_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "posts_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_label";
  ALTER TABLE "_posts_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_posts_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_posts_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_posts_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_posts_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "_posts_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "_posts_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "_posts_v_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_label";
  ALTER TABLE "products_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "products_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "products_blocks_cta_center_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "products_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "products_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "products_blocks_cta_left_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "products_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_type";
  ALTER TABLE "products_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_new_tab";
  ALTER TABLE "products_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_url";
  ALTER TABLE "products_blocks_cta_right_locales" DROP COLUMN IF EXISTS "link_label";
  DROP TYPE "public"."enum_pages_blocks_cta_right_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_cta_right_link_type";
  DROP TYPE "public"."enum_posts_blocks_cta_right_link_type";
  DROP TYPE "public"."enum__posts_v_blocks_cta_right_link_type";
  DROP TYPE "public"."enum_products_blocks_cta_right_link_type";`)
}
