name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URI: file:./data.sqlite3
      PAYLOAD_SECRET: temp-secret-for-building-purposes-only-123456
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v6
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run check
        run: just check

      - name: Run build
        run: just build
